import os

BASE_DIR = os.getcwd()

OHLC_FOLDER = os.path.join(BASE_DIR, 'OHLCFiles')
INDEX_OHLC_FOLDER = os.path.join(BASE_DIR, 'IndexOHLCFiles')
INDEX_FILES_FOLDER = os.path.join(BASE_DIR, 'index-files')
FB_FOLDER = os.path.join(BASE_DIR, 'FBFiles')

INDEX_MAPPING = {
                        'INDUSTRY-Automobiles': 'AUTO-I',
                        'INDUSTRY-Automobile Components': 'AUTOCOMP-I',
                        'INDUSTRY-Specialty Retail': 'SPECRETAI-I',
                        'INDUSTRY-Consumer Staples Distribution & Retail': 'CONSTAPDIST-I',
                        'INDUSTRY-Broadline Retail': 'BROADRETAI-I',
                        'INDUSTRY-Food Products': 'FOODPROD-I',
                        'INDUSTRY-Beverages': 'BEVERAGE-I',
                        'INDUSTRY-Building Products': 'BUILDPROD-I',
                        'INDUSTRY-Construction & Engineering': 'CONSENGINE-I',
                        'INDUSTRY-Chemicals': 'CHEMICAL-I',
                        'INDUSTRY-Textiles, Apparel & Luxury Goods': 'TEXAPPLUX-I',
                        'INDUSTRY-Containers & Packaging': 'CONTAINPKG-I',
                        'INDUSTRY-Oil, Gas & Consumable Fuels': 'ONGCONFUEL-I',
                        'INDUSTRY-Household Products': 'HOUSEPROD-I',
                        'INDUSTRY-Personal Care Products': 'PERCARPROD-I',
                        'INDUSTRY-Pharmaceuticals': 'PHARMAC-I',
                        'INDUSTRY-Health Care Equipment & Supplies': 'HLTCAEQSUPP-I',
                        'INDUSTRY-Tobacco': 'TOBACCO-I',
                        'INDUSTRY-Household Durables': 'HOUSEDUR-I',
                        'INDUSTRY-Technology Hardware, Storage & Peripherals': 'TECHARDSOFTPER-I',
                        'INDUSTRY-Software': 'SOFTWARE-I',
                        'INDUSTRY-Electronic Equipment, Instruments & Components': 'ELEEQINSCMP-I',
                        'INDUSTRY-Commercial Services & Supplies': 'COMSERVSUP-I',
                        'INDUSTRY-Electrical Equipment': 'ELECEQUIP-I',
                        'INDUSTRY-IT Services': 'ITSERV-I',
                        'INDUSTRY-Machinery': 'MACHINERY-I',
                        'INDUSTRY-Insurance': 'INSURAN-I',
                        'INDUSTRY-Banks': 'BANKS-I',
                        'INDUSTRY-Financial Services': 'FINSERV-I',
                        'INDUSTRY-Capital Markets': 'CAPIMKT-I',
                        'INDUSTRY-Metals & Mining': 'METAMINE-I',
                        'INDUSTRY-Energy Equipment & Services': 'ENEQUSERV-I',
                        'INDUSTRY-Electric Utilities': 'ELECUTIL-I',
                        'INDUSTRY-Diversified Telecommunication Services': 'DIVTELECOMSERV-I',
                        'INDUSTRY-Independent Power and Renewable Electricity Producers': 'INDPOWRENEL-I',
                        'INDUSTRY-Paper & Forest Products': 'PAPFORPROD-I',
                        'INDUSTRY-Health Care Providers & Services': 'HLTCAPROSERV-I',
                        'INDUSTRY-Marine Transportation': 'MARITRA-I',
                        'INDUSTRY-Ground Transportation': 'GRNDTRAN-SI',
                        'INDUSTRY-Air Freight & Logistics': 'AIRFRELOGIS-I',
                        'INDUSTRY-Hotels, Restaurants & Leisure': 'HOTRESLEIS-I',
                        'INDUSTRY-Transportation Infrastructure': 'TRANSINFRA-I',
                        'INDUSTRY-Interactive Media & Services': 'INTMEDSERV-I',
                        'INDUSTRY-Diversified Consumer Services': 'DIVERCONSERV-I',
                        'INDUSTRY-Real Estate Management & Development': 'RESMGMDEV-I',
                        'INDUSTRY-Entertainment': 'ENTERTAIN-I',
                        'INDUSTRY-Retail REITs': 'RETIALREIT-I',
                        'INDUSTRY-Media': 'MEDIA-I',
                        'INDUSTRY-Gas Utilities': 'GASUTIL-I',
                        'INDUSTRY-Leisure Products': 'LEISPROD-I',
                        'SUBINDUSTRY-Auto - LCVs/HCVs': 'AUTLCVHCV-SI',
                        'SUBINDUSTRY-Auto - Cars & Jeeps': 'AUTCARJEE-SI',
                        'SUBINDUSTRY-Motorcycle Manufacturers': 'MOTORMFG-SI',
                        'SUBINDUSTRY-Automotive Parts & Equipment': 'AUTPEQUIP-SI',
                        'SUBINDUSTRY-Tires & Rubber': 'TIRERUB-SI',
                        'SUBINDUSTRY-Carbon Black': 'CARBLCK-SI',
                        'SUBINDUSTRY-Other Specialty Retail': 'OTHSPECRETL-SI',
                        'SUBINDUSTRY-Retail - Departmental Stores': 'RETDEPTSTO-SI',
                        'SUBINDUSTRY-Retail - Apparel': 'RETAPPAREL-SI',
                        'SUBINDUSTRY-Retail - Apparel/Accessories': 'RETAPPARACC-SI',
                        'SUBINDUSTRY-Trading': 'TRADING-SI',
                        'SUBINDUSTRY-Plantations': 'PLANTATIO-SI',
                        'SUBINDUSTRY-Distillers & Vintners': 'DISTILVINTN-SI',
                        'SUBINDUSTRY-Aqua & Horticulture': 'AQUAHORTIC-SI',
                        'SUBINDUSTRY-Edible Oils': 'EDIBLEOIL-SI',
                        'SUBINDUSTRY-Agricultural Products & Services': 'AGRIPROSER-SI',
                        'SUBINDUSTRY-Soft Drinks & Non-alcoholic Beverages': 'SODRINALCBEV-SI',
                        'SUBINDUSTRY-Packaged Foods & Meats': 'PKGFOODMEAT-SI',
                        'SUBINDUSTRY-Sugar': 'SUGAR-SI',
                        'SUBINDUSTRY-Cement & Products': 'CEMPROD-SI',
                        'SUBINDUSTRY-Tiles & Granites': 'TILEGRANI-SI',
                        'SUBINDUSTRY-Decoratives & Laminates': 'DECOLAMIN-SI',
                        'SUBINDUSTRY-Paints': 'PAINTS-SI',
                        'SUBINDUSTRY-Building Products': 'BUILDPROD-SI',
                        'SUBINDUSTRY-Construction & Engineering': 'CONSENGINE-SI',
                        'SUBINDUSTRY-Commodity Chemicals': 'COMMOCHEM-SI',
                        'SUBINDUSTRY-Specialty Chemicals': 'SPECHEM-SI',
                        'SUBINDUSTRY-Fertilizers & Agricultural Chemicals': 'FERAGRICHM-SI',
                        'SUBINDUSTRY-Diversified Chemicals': 'DIVERCHEM-SI',
                        'SUBINDUSTRY-Textiles': 'TEXTILES-SI',
                        'SUBINDUSTRY-Paper & Plastic Packaging Products & Materials': 'PPLPGPROMAT-SI',
                        'SUBINDUSTRY-Oil & Gas Refining & Marketing': 'ONGREFMKT-SI',
                        'SUBINDUSTRY-Household Products': 'HOUSEPROD-SI',
                        'SUBINDUSTRY-Personal Care Products': 'PERCARPROD-SI',
                        'SUBINDUSTRY-Pharmaceuticals': 'PHARMAC-SI',
                        'SUBINDUSTRY-Apparel, Accessories & Luxury Goods': 'APPACCLUX-SI',
                        'SUBINDUSTRY-Health Care Supplies': 'HLTCARESUPP-SI',
                        'SUBINDUSTRY-Tobacco': 'TOBACCO-SI',
                        'SUBINDUSTRY-Household Appliances': 'HOUSEAPPLI-SI',
                        'SUBINDUSTRY-Technology Hardware, Storage & Peripherals': 'TECHARDSOFTPER-SI',
                        'SUBINDUSTRY-Systems Software': 'SYSOFT-SI',
                        'SUBINDUSTRY-Electronic Equipment & Instruments': 'ELECEQUINS-SI',
                        'SUBINDUSTRY-Office Services & Supplies': 'OFFSERVSUPP-SI',
                        'SUBINDUSTRY-Consumer Electronics': 'CONSELEC-SI',
                        'SUBINDUSTRY-Electrical Components & Equipment': 'ELECOMEQU-SI',
                        'SUBINDUSTRY-Health Care Equipment': 'HLTCAREQU-SI',
                        'SUBINDUSTRY-Application Software': 'APPLICSOFT-SI',
                        'SUBINDUSTRY-IT Consulting & Other Services': 'ITCONSOTHSV-SI',
                        'SUBINDUSTRY-Research & Consulting Services': 'RESCONSERV-SI',
                        'SUBINDUSTRY-Industrial Machinery & Supplies & Components': 'INDMCHSUPCOM-SI',
                        'SUBINDUSTRY-Finance - Life Insurance': 'FINLIFINS-SI',
                        'SUBINDUSTRY-Private Banks': 'PVTBNK-SI',
                        'SUBINDUSTRY-Finance - Term Lending': 'FINTERLEND-SI',
                        'SUBINDUSTRY-Finance - Mutual Funds': 'FINMF-SI',
                        'SUBINDUSTRY-Investment Trusts': 'INVTRUST-SI',
                        'SUBINDUSTRY-Finance - Housing': 'FINHSG-SI',
                        'SUBINDUSTRY-Finance & Investments': 'FININVTS-SI',
                        'SUBINDUSTRY-PSU Banks': 'PSUBNK-SI',
                        'SUBINDUSTRY-Finance - Non Life Insurance': 'FINNONLIFINS-SI',
                        'SUBINDUSTRY-Reinsurance': 'REINSURE-SI',
                        'SUBINDUSTRY-Financial Exchanges & Data': 'FINEXCHDATA-SI',
                        'SUBINDUSTRY-Bearings': 'BEARINGS-SI',
                        'SUBINDUSTRY-Ferro Alloys': 'FERALLO-SI',
                        'SUBINDUSTRY-Fasteners': 'FASTENERS-SI',
                        'SUBINDUSTRY-Industrial Gases': 'INDUSGAS-SI',
                        'SUBINDUSTRY-Metal, Glass & Plastic Containers': 'METGLAPLACON-SI',
                        'SUBINDUSTRY-Aluminum': 'ALUMINIUM-SI',
                        'SUBINDUSTRY-Precious Metals & Minerals': 'PRECMETMIN-SI',
                        'SUBINDUSTRY-Diversified Metals & Mining': 'DIVERMETMIN-SI',
                        'SUBINDUSTRY-Oil & Gas Drilling': 'ONGDRILL-SI',
                        'SUBINDUSTRY-Electric Utilities': 'ELECUTILI-SI',
                        'SUBINDUSTRY-Telecommunications - Equipment': 'TELECOMEQU-SI',
                        'SUBINDUSTRY-Heavy Electrical Equipment': 'HVYELECEQUIP-SI',
                        'SUBINDUSTRY-Renewable Electricity': 'RENEWELEC-SI',
                        'SUBINDUSTRY-Copper': 'COPPER-SI',
                        'SUBINDUSTRY-Integrated Telecommunication Services': 'INTGTELCOSVC-SI',
                        'SUBINDUSTRY-Infrastructure - General': 'INFRAGEN-SI',
                        'SUBINDUSTRY-Steel': 'STEEL-SI',
                        'SUBINDUSTRY-Paper Products': 'PAPERPROD-SI1',
                        'SUBINDUSTRY-Livestock - Hatcheries/Poultry': 'LIVHATCHPOUL-SI',
                        'SUBINDUSTRY-Health Care Facilities': 'HLTCAREFACIL-SI',
                        'SUBINDUSTRY-Marine Transportation': 'MARITRA-SI',
                        'SUBINDUSTRY-Transport - Road': 'TRAROAD-SI',
                        'SUBINDUSTRY-Transport - Air': 'TRAAIR-SI',
                        'SUBINDUSTRY-Hotels, Resorts & Cruise Lines': 'HOTRESCRUIS-SI',
                        'SUBINDUSTRY-Marine Ports & Services': 'MARIPORSV-SI',
                        'SUBINDUSTRY-Diversified Support Services': 'DIVERSUPSER-SI',
                        'SUBINDUSTRY-Interactive Media & Services': 'INTMEDSERV-SI',
                        'SUBINDUSTRY-Fire Protection Equipment': 'FIRPROTEQU-SI',
                        'SUBINDUSTRY-LPG Bottling/Distribution': 'LPGBOTDIST-SI',
                        'SUBINDUSTRY-Commercial Printing': 'COMMERPRINT-SI',
                        'SUBINDUSTRY-Agricultural & Farm Machinery': 'AGRIFARMCH-SI',
                        'SUBINDUSTRY-Diversified Financial Services': 'DIVERFINSER-SI',
                        'SUBINDUSTRY-E-Commerce - Retail': 'ECOMRET-SI',
                        'SUBINDUSTRY-Education Services': 'EDUSERV-SI',
                        'SUBINDUSTRY-Real Estate Development': 'REALSTATDEV-SI',
                        'SUBINDUSTRY-Waste Management': 'WASTEMAN-SI',
                        'SUBINDUSTRY-Multi-Sector Holdings': 'MULTSECTHLD-SI',
                        'SUBINDUSTRY-Fintech': 'FINTEC-SI',
                        'SUBINDUSTRY-Health Care Services': 'HLTCARESERV-SI',
                        'SUBINDUSTRY-Digital Entertainment': 'DIGIENTER-SI',
                        'SUBINDUSTRY-Leisure Facilities': 'LEISFACIL-SI',
                        'SUBINDUSTRY-Dairy': 'DAIRY-SI',
                        'SUBINDUSTRY-Marine Foods': 'MARIFOOD-SI',
                        'SUBINDUSTRY-Road Infrastructure': 'ROADINFRA-SI',
                        'SUBINDUSTRY-Retail REITs': 'RETAILREIT-SI',
                        'SUBINDUSTRY-Specialized Finance': 'SPECIFIN-SI',
                        'SUBINDUSTRY-Railway Wagons and Wans': 'RAILWAGWAN-SI',
                        'SUBINDUSTRY-Footwear': 'FOOTWEAR-SI',
                        'SUBINDUSTRY-Advertising': 'ADVERT-SI',
                        'SUBINDUSTRY-Construction Machinery & Heavy Transportation Equipment': 'CONMCHVYTRN-SI',
                        'SUBINDUSTRY-Home Furnishings': 'HOMFURNIS-SI',
                        'SUBINDUSTRY-Gas Utilities': 'GASUTIL-SI',
                        'SUBINDUSTRY-Insurance Brokers': 'INSURBROK-SI',
                        'SUBINDUSTRY-Leisure Products': 'LEISPROD-SI',
                        'SUBINDUSTRY-Micro Finance Institutions': 'MICROFININS-SI',
                        'SUBINDUSTRY-Oil & Gas Equipment & Services': 'ONGEQUSERV-SI',
                        'SUBINDUSTRY-Diversified Capital Markets': 'DIVERCAPMKT-SI',
                        'SECTOR-Consumer Discretionary': 'CONSDISC-S',
                        'SECTOR-Consumer Staples': 'CONSTAPL-S',
                        'SECTOR-Industrials': 'INDUSTRIAL-S',
                        'SECTOR-Materials': 'MATERIALS-S',
                        'SECTOR-Energy': 'ENERGY-S',
                        'SECTOR-Health Care': 'HLTHCARE-S',
                        'SECTOR-Information Technology': 'INFOTEC-S',
                        'SECTOR-Financials': 'FINANCIALS-S',
                        'SECTOR-Utilities': 'UTILITIES-S',
                        'SECTOR-Communication Services': 'COMMSERV-S',
                        'SECTOR-Real Estate': 'REALESTATE-S',
                        'SUBSECTOR-Automobiles & Components': 'AUTOCOMP-SS',
                        'SUBSECTOR-Consumer Discretionary Distribution & Retail': 'CONSDDRETA-SS',
                        'SUBSECTOR-Consumer Staples Distribution & Retail': 'CONSTAPDISRE-SS',
                        'SUBSECTOR-Food, Beverage & Tobacco': 'FOOBEVTOBA-SS',
                        'SUBSECTOR-Capital Goods': 'CAPIGOOD-SS',
                        'SUBSECTOR-Materials': 'MATERIAL-SS',
                        'SUBSECTOR-Consumer Durables & Apparel': 'CONSDURAPP-SS',
                        'SUBSECTOR-Energy': 'ENERGY-SS',
                        'SUBSECTOR-Household & Personal Products': 'HOUSPERS-SS',
                        'SUBSECTOR-Pharmaceuticals, Biotechnology & Life Sciences': 'PHARMBIOLIFS-SS',
                        'SUBSECTOR-Health Care Equipment & Services': 'HLTCAREQUSV-SS',
                        'SUBSECTOR-Technology Hardware & Equipment': 'TECHARDEQUI-SS',
                        'SUBSECTOR-Software & Services': 'SOFTSERV-SS',
                        'SUBSECTOR-Commercial & Professional Services': 'COMPRFSERV-SS',
                        'SUBSECTOR-Insurance': 'INSURANCE-SS',
                        'SUBSECTOR-Banks': 'BANKS-SS',
                        'SUBSECTOR-Financial Services': 'FINSERV-SS',
                        'SUBSECTOR-Utilities': 'UTILITIES-SS',
                        'SUBSECTOR-Telecommunication Services': 'TELECOSERV-SS',
                        'SUBSECTOR-Transportation': 'TRANSPORT-SS',
                        'SUBSECTOR-Consumer Services': 'CONSERV-SS',
                        'SUBSECTOR-Media & Entertainment': 'MEDIAENT-SS',
                        'SUBSECTOR-Real Estate Management & Development': 'RESMGMDEV-SS',
                        'SUBSECTOR-Equity Real Estate Investment Trusts (REITs)': 'EQREITS-SS'
                    }